version: "3"
services:
  node-a:
    build: .
    image: angra:latest
    environment: 
      - ANGRA_NAME=a@angra1.com
      - ANGRA_COOKIE=teste
    container_name: angra1.com
    networks:
      - angra_lan
    ports: 
      - 1234-1236:1234-1236

networks:
  angra_lan:
    driver: bridge
  local_lan:
    driver: host