-define(Version, "1.0").
-define(HashSize, 10000).
-define(SizeOfDocPos, 4).
-define(SizeOfDocKey, 14).
-define(SizeOfPosting, 18).
-define(SizeOfCount, 4).
-define(SizeOfWord, 60).
-define(SizeOfHeader, 5).
-define(SizeOfVersion, 5).
-define(SizeOfTerm, 72).
-define(SizeOfPointer, 8).

-record(posting, {docKey, docPos}).
-record(posting_ext, {docKey, docPos, fieldStart, fieldEnd}).
-record(token, {word, docPos}).
-record(token_ext, {word, docPos, fieldStart, fieldEnd}).
-record(term, {word, postings, count}).
-record(bucket, {terms, count}).