-define(SizeOfPointer, 8).
-define(SizeOfHeader, 66).
-define(OrderSize, 2).
-define(KeySize, 32).
-define(Node, 0).
-define(Leaf, 1).
-define(SizeOfSize, 8).
-define(DefaultOrder, 256).
-define(DefaultVerSize, 8).
-define(DefaultMaxSize, 16).

-record(dbsettings, {dbname, sizeinbytes, sizeversion}).
-record(btree, {order, curNode}).
-record(node, {keys, nodePointers}).
-record(leaf, {keys, docPointers, leafPointer, versions}).
